[2024-12-28T12:45:52.592+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-28T12:45:52.609+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline manual__2024-12-27T18:18:57.309903+00:00 [queued]>
[2024-12-28T12:45:52.618+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline manual__2024-12-27T18:18:57.309903+00:00 [queued]>
[2024-12-28T12:45:52.620+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-28T12:45:52.631+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): l30_dump_pipeline> on 2024-12-27 18:18:57.309903+00:00
[2024-12-28T12:45:52.640+0000] {standard_task_runner.py:72} INFO - Started process 25204 to run task
[2024-12-28T12:45:52.642+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'l30d_dump_pipeline', 'l30_dump_pipeline', 'manual__2024-12-27T18:18:57.309903+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/L30D_data_dump.py', '--cfg-path', '/tmp/tmpn87v2nep']
[2024-12-28T12:45:52.644+0000] {standard_task_runner.py:105} INFO - Job 134: Subtask l30_dump_pipeline
[2024-12-28T12:45:52.685+0000] {task_command.py:467} INFO - Running <TaskInstance: l30d_dump_pipeline.l30_dump_pipeline manual__2024-12-27T18:18:57.309903+00:00 [running]> on host 0a732720d1ba
[2024-12-28T12:45:52.750+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='l30d_dump_pipeline' AIRFLOW_CTX_TASK_ID='l30_dump_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T18:18:57.309903+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-27T18:18:57.309903+00:00'
[2024-12-28T12:45:52.753+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-28T12:45:52.754+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-28T12:45:52.755+0000] {logging_mixin.py:190} INFO - Current task name:l30_dump_pipeline state:running start_date:2024-12-28 12:45:52.611060+00:00
[2024-12-28T12:45:52.756+0000] {logging_mixin.py:190} INFO - Dag name:l30d_dump_pipeline and current dag run status:running
[2024-12-28T12:45:52.757+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-28T12:46:01.624+0000] {logging_mixin.py:190} INFO - <pyspark.sql.session.SparkSession object at 0x7fbafde836a0>
[2024-12-28T12:46:01.626+0000] {logging_mixin.py:190} INFO - Spark session created successfully
[2024-12-28T12:46:03.792+0000] {java_gateway.py:2273} INFO - Callback Server Starting
[2024-12-28T12:46:03.794+0000] {java_gateway.py:2275} INFO - Socket listening on ('127.0.0.1', 43023)
[2024-12-28T12:46:05.994+0000] {clientserver.py:561} INFO - Python Server ready to receive messages
[2024-12-28T12:46:05.996+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:46:06.789+0000] {logging_mixin.py:190} INFO - True
[2024-12-28T12:46:06.791+0000] {logging_mixin.py:190} INFO - Table historical_stock_data already exists
[2024-12-28T12:46:06.807+0000] {logging_mixin.py:190} INFO - Successfully appended 0 rows to historical_stock_data
[2024-12-28T12:54:54.010+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:54:58.886+0000] {logging_mixin.py:190} INFO - True
[2024-12-28T12:54:58.892+0000] {logging_mixin.py:190} INFO - Table historical_stock_data already exists
[2024-12-28T12:54:58.926+0000] {logging_mixin.py:190} INFO - Successfully appended 63 rows to historical_stock_data
[2024-12-28T12:55:14.313+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:55:14.967+0000] {logging_mixin.py:190} INFO - True
[2024-12-28T12:55:14.970+0000] {logging_mixin.py:190} INFO - Table historical_stock_data already exists
[2024-12-28T12:55:14.976+0000] {logging_mixin.py:190} INFO - Successfully appended 63 rows to historical_stock_data
[2024-12-28T12:56:06.340+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:56:07.004+0000] {logging_mixin.py:190} INFO - True
[2024-12-28T12:56:07.007+0000] {logging_mixin.py:190} INFO - Table historical_stock_data already exists
[2024-12-28T12:56:07.019+0000] {logging_mixin.py:190} INFO - Successfully appended 63 rows to historical_stock_data
[2024-12-28T12:57:54.137+0000] {job.py:229} INFO - Heartbeat recovered after 24.69 seconds
[2024-12-28T12:58:18.451+0000] {job.py:229} INFO - Heartbeat recovered after 24.32 seconds
[2024-12-28T12:59:19.664+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 284, in spark_l30d
    # query.awaitTermination()
  File "/opt/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = cf801690-578b-484c-bb66-bd01a9432b6f, runId = 10261f91-32b7-47df-b67e-2ff83c496440] terminated with exception: Failed to create new KafkaAdminClient
[2024-12-28T12:59:19.950+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-28T12:59:19.952+0000] {logging_mixin.py:190} INFO - Task start:2024-12-28 12:45:52.611060+00:00 end:2024-12-28 12:59:19.917559+00:00 duration:807.306499
[2024-12-28T12:59:19.959+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): l30_dump_pipeline> dag:<DAG: l30d_dump_pipeline> dagrun:<DagRun l30d_dump_pipeline @ 2024-12-27 18:18:57.309903+00:00: manual__2024-12-27T18:18:57.309903+00:00, state:running, queued_at: 2024-12-27 18:18:57.339276+00:00. externally triggered: True>
[2024-12-28T12:59:19.965+0000] {logging_mixin.py:190} INFO - Failure caused by [STREAM_FAILED] Query [id = cf801690-578b-484c-bb66-bd01a9432b6f, runId = 10261f91-32b7-47df-b67e-2ff83c496440] terminated with exception: Failed to create new KafkaAdminClient
[2024-12-28T12:59:19.967+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=l30d_dump_pipeline, task_id=l30_dump_pipeline, run_id=manual__2024-12-27T18:18:57.309903+00:00, execution_date=20241227T181857, start_date=20241228T124552, end_date=20241228T125919
[2024-12-28T12:59:20.112+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-28T12:59:20.126+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 134 for task l30_dump_pipeline ([STREAM_FAILED] Query [id = cf801690-578b-484c-bb66-bd01a9432b6f, runId = 10261f91-32b7-47df-b67e-2ff83c496440] terminated with exception: Failed to create new KafkaAdminClient; 25204)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 284, in spark_l30d
    # query.awaitTermination()
  File "/opt/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = cf801690-578b-484c-bb66-bd01a9432b6f, runId = 10261f91-32b7-47df-b67e-2ff83c496440] terminated with exception: Failed to create new KafkaAdminClient
[2024-12-28T12:59:20.210+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-28T12:59:20.348+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-28T12:59:20.351+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
