[2024-12-28T12:40:51.586+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-28T12:40:51.617+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: realtime_dump_pipeline.realtime_pipeline scheduled__2024-12-27T00:00:00+00:00 [queued]>
[2024-12-28T12:40:51.630+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: realtime_dump_pipeline.realtime_pipeline scheduled__2024-12-27T00:00:00+00:00 [queued]>
[2024-12-28T12:40:51.632+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-28T12:40:51.649+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): realtime_pipeline> on 2024-12-27 00:00:00+00:00
[2024-12-28T12:40:51.661+0000] {standard_task_runner.py:72} INFO - Started process 24135 to run task
[2024-12-28T12:40:51.685+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'realtime_dump_pipeline', 'realtime_pipeline', 'scheduled__2024-12-27T00:00:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/realtime_data_dump.py', '--cfg-path', '/tmp/tmp06qs3az4']
[2024-12-28T12:40:51.693+0000] {standard_task_runner.py:105} INFO - Job 130: Subtask realtime_pipeline
[2024-12-28T12:40:51.799+0000] {task_command.py:467} INFO - Running <TaskInstance: realtime_dump_pipeline.realtime_pipeline scheduled__2024-12-27T00:00:00+00:00 [running]> on host 0a732720d1ba
[2024-12-28T12:40:52.015+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='realtime_dump_pipeline' AIRFLOW_CTX_TASK_ID='realtime_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-27T00:00:00+00:00'
[2024-12-28T12:40:52.020+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-28T12:40:52.021+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-28T12:40:52.023+0000] {logging_mixin.py:190} INFO - Current task name:realtime_pipeline state:running start_date:2024-12-28 12:40:51.619143+00:00
[2024-12-28T12:40:52.024+0000] {logging_mixin.py:190} INFO - Dag name:realtime_dump_pipeline and current dag run status:running
[2024-12-28T12:40:52.026+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-28T12:41:03.782+0000] {logging_mixin.py:190} INFO - <pyspark.sql.session.SparkSession object at 0x7fbafde8b250>
[2024-12-28T12:41:03.783+0000] {logging_mixin.py:190} INFO - Spark session created successfully
[2024-12-28T12:41:06.107+0000] {logging_mixin.py:190} INFO - Reading from topic stock
[2024-12-28T12:41:07.001+0000] {java_gateway.py:2273} INFO - Callback Server Starting
[2024-12-28T12:41:07.004+0000] {java_gateway.py:2275} INFO - Socket listening on ('127.0.0.1', 46601)
[2024-12-28T12:41:10.066+0000] {clientserver.py:561} INFO - Python Server ready to receive messages
[2024-12-28T12:41:10.068+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:41:12.223+0000] {logging_mixin.py:190} INFO - Table stock_prices already exists
[2024-12-28T12:41:12.237+0000] {logging_mixin.py:190} INFO - Successfully appended 143 rows to stock_prices
[2024-12-28T12:41:12.445+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:41:15.733+0000] {logging_mixin.py:190} INFO - Table stock_prices already exists
[2024-12-28T12:41:15.574+0000] {logging_mixin.py:190} INFO - Successfully appended 2 rows to stock_prices
[2024-12-28T12:41:16.272+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:41:17.005+0000] {logging_mixin.py:190} INFO - Table stock_prices already exists
[2024-12-28T12:41:17.010+0000] {logging_mixin.py:190} INFO - Successfully appended 1 rows to stock_prices
[2024-12-28T12:41:46.472+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:41:47.084+0000] {logging_mixin.py:190} INFO - Table stock_prices already exists
[2024-12-28T12:41:47.090+0000] {logging_mixin.py:190} INFO - Successfully appended 1 rows to stock_prices
[2024-12-28T12:41:47.491+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:41:48.099+0000] {logging_mixin.py:190} INFO - Table stock_prices already exists
[2024-12-28T12:41:48.106+0000] {logging_mixin.py:190} INFO - Successfully appended 1 rows to stock_prices
[2024-12-28T12:41:48.514+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:41:49.135+0000] {logging_mixin.py:190} INFO - Table stock_prices already exists
[2024-12-28T12:41:49.140+0000] {logging_mixin.py:190} INFO - Successfully appended 1 rows to stock_prices
[2024-12-28T12:41:49.529+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:41:50.123+0000] {logging_mixin.py:190} INFO - Table stock_prices already exists
[2024-12-28T12:41:50.128+0000] {logging_mixin.py:190} INFO - Successfully appended 1 rows to stock_prices
[2024-12-28T12:41:50.566+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:41:51.166+0000] {logging_mixin.py:190} INFO - Table stock_prices already exists
[2024-12-28T12:41:51.175+0000] {logging_mixin.py:190} INFO - Successfully appended 1 rows to stock_prices
[2024-12-28T12:41:51.604+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2024-12-28T12:41:52.223+0000] {logging_mixin.py:190} INFO - Table stock_prices already exists
[2024-12-28T12:41:52.232+0000] {logging_mixin.py:190} INFO - Successfully appended 1 rows to stock_prices
[2024-12-28T12:57:54.138+0000] {job.py:229} INFO - Heartbeat recovered after 22.66 seconds
[2024-12-28T12:58:18.449+0000] {job.py:229} INFO - Heartbeat recovered after 24.32 seconds
[2024-12-28T12:59:19.746+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 12, in data_dump_pipeline
    spark_streaming(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 161, in spark_streaming
    query.awaitTermination()
  File "/opt/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = dc07e748-55c4-45b7-a144-f4422bc347e4, runId = bb42e77e-9d63-443b-9ecd-4a2aae65b303] terminated with exception: Failed to create new KafkaAdminClient
[2024-12-28T12:59:20.203+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-28T12:59:20.206+0000] {logging_mixin.py:190} INFO - Task start:2024-12-28 12:40:51.619143+00:00 end:2024-12-28 12:59:20.181553+00:00 duration:1108.56241
[2024-12-28T12:59:20.213+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): realtime_pipeline> dag:<DAG: realtime_dump_pipeline> dagrun:<DagRun realtime_dump_pipeline @ 2024-12-27 00:00:00+00:00: scheduled__2024-12-27T00:00:00+00:00, state:running, queued_at: 2024-12-28 12:40:30.306441+00:00. externally triggered: False>
[2024-12-28T12:59:20.220+0000] {logging_mixin.py:190} INFO - Failure caused by [STREAM_FAILED] Query [id = dc07e748-55c4-45b7-a144-f4422bc347e4, runId = bb42e77e-9d63-443b-9ecd-4a2aae65b303] terminated with exception: Failed to create new KafkaAdminClient
[2024-12-28T12:59:20.223+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=realtime_dump_pipeline, task_id=realtime_pipeline, run_id=scheduled__2024-12-27T00:00:00+00:00, execution_date=20241227T000000, start_date=20241228T124051, end_date=20241228T125920
[2024-12-28T12:59:20.391+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-28T12:59:20.400+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 130 for task realtime_pipeline ([STREAM_FAILED] Query [id = dc07e748-55c4-45b7-a144-f4422bc347e4, runId = bb42e77e-9d63-443b-9ecd-4a2aae65b303] terminated with exception: Failed to create new KafkaAdminClient; 24135)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 12, in data_dump_pipeline
    spark_streaming(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 161, in spark_streaming
    query.awaitTermination()
  File "/opt/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = dc07e748-55c4-45b7-a144-f4422bc347e4, runId = bb42e77e-9d63-443b-9ecd-4a2aae65b303] terminated with exception: Failed to create new KafkaAdminClient
[2024-12-28T12:59:20.501+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-28T12:59:20.646+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-28T12:59:20.649+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
