[2024-12-27T18:01:43.560+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-27T18:01:43.574+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline manual__2024-12-26T20:33:44.624076+00:00 [queued]>
[2024-12-27T18:01:43.581+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline manual__2024-12-26T20:33:44.624076+00:00 [queued]>
[2024-12-27T18:01:43.582+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-27T18:01:43.594+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): l30_dump_pipeline> on 2024-12-26 20:33:44.624076+00:00
[2024-12-27T18:01:43.600+0000] {standard_task_runner.py:72} INFO - Started process 167 to run task
[2024-12-27T18:01:43.604+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'l30d_dump_pipeline', 'l30_dump_pipeline', 'manual__2024-12-26T20:33:44.624076+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/L30D_data_dump.py', '--cfg-path', '/tmp/tmpg5rllzyo']
[2024-12-27T18:01:43.606+0000] {standard_task_runner.py:105} INFO - Job 104: Subtask l30_dump_pipeline
[2024-12-27T18:01:43.646+0000] {task_command.py:467} INFO - Running <TaskInstance: l30d_dump_pipeline.l30_dump_pipeline manual__2024-12-26T20:33:44.624076+00:00 [running]> on host c36613fa3dab
[2024-12-27T18:01:43.704+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='l30d_dump_pipeline' AIRFLOW_CTX_TASK_ID='l30_dump_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T20:33:44.624076+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T20:33:44.624076+00:00'
[2024-12-27T18:01:43.706+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-27T18:01:43.707+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-27T18:01:43.708+0000] {logging_mixin.py:190} INFO - Current task name:l30_dump_pipeline state:running start_date:2024-12-27 18:01:43.575670+00:00
[2024-12-27T18:01:43.709+0000] {logging_mixin.py:190} INFO - Dag name:l30d_dump_pipeline and current dag run status:running
[2024-12-27T18:01:43.710+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-27T18:01:49.651+0000] {logging_mixin.py:190} INFO - <pyspark.sql.session.SparkSession object at 0x7f759cc66fe0>
[2024-12-27T18:01:49.653+0000] {logging_mixin.py:190} INFO - Spark session created successfully
[2024-12-27T18:01:51.417+0000] {java_gateway.py:2273} INFO - Callback Server Starting
[2024-12-27T18:01:51.419+0000] {java_gateway.py:2275} INFO - Socket listening on ('127.0.0.1', 36535)
[2024-12-27T18:01:59.014+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 282, in spark_l30d
    query.awaitTermination()
  File "/opt/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = 6ed098f9-5ead-4a32-9fd1-ddbc3f477ea6, runId = ce48225f-96f6-4253-afd2-0c6bed66b811] terminated with exception: Failed to create new KafkaAdminClient
[2024-12-27T18:01:59.032+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-27T18:01:59.033+0000] {logging_mixin.py:190} INFO - Task start:2024-12-27 18:01:43.575670+00:00 end:2024-12-27 18:01:59.031833+00:00 duration:15.456163
[2024-12-27T18:01:59.035+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): l30_dump_pipeline> dag:<DAG: l30d_dump_pipeline> dagrun:<DagRun l30d_dump_pipeline @ 2024-12-26 20:33:44.624076+00:00: manual__2024-12-26T20:33:44.624076+00:00, state:running, queued_at: 2024-12-26 20:33:44.632595+00:00. externally triggered: True>
[2024-12-27T18:01:59.039+0000] {logging_mixin.py:190} INFO - Failure caused by [STREAM_FAILED] Query [id = 6ed098f9-5ead-4a32-9fd1-ddbc3f477ea6, runId = ce48225f-96f6-4253-afd2-0c6bed66b811] terminated with exception: Failed to create new KafkaAdminClient
[2024-12-27T18:01:59.040+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=l30d_dump_pipeline, task_id=l30_dump_pipeline, run_id=manual__2024-12-26T20:33:44.624076+00:00, execution_date=20241226T203344, start_date=20241227T180143, end_date=20241227T180159
[2024-12-27T18:01:59.057+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-27T18:01:59.059+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 104 for task l30_dump_pipeline ([STREAM_FAILED] Query [id = 6ed098f9-5ead-4a32-9fd1-ddbc3f477ea6, runId = ce48225f-96f6-4253-afd2-0c6bed66b811] terminated with exception: Failed to create new KafkaAdminClient; 167)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 282, in spark_l30d
    query.awaitTermination()
  File "/opt/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = 6ed098f9-5ead-4a32-9fd1-ddbc3f477ea6, runId = ce48225f-96f6-4253-afd2-0c6bed66b811] terminated with exception: Failed to create new KafkaAdminClient
[2024-12-27T18:01:59.110+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-27T18:01:59.127+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-27T18:01:59.132+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
